---
- name: install prerequisites
  yum: name={{ item }} state=installed
  with_items: logstash_prereqs

- name: create logstash yum repo
  template: src=logstash.repo.j2 dest=/etc/yum.repos.d/logstash.repo

- name: import rpm gpg key
  rpm_key: key={{ logstash_rpm_gpg_key }} state=present

- name: install logstash
  yum: name=logstash state=installed
